# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'



steps:
# Add this task to install the .NET 9.0 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 9.x SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x' # This specifies the .NET 9 SDK
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
